### ISSUE TITLE
Privacy Badger not as effective for some sites

### ISSUE THREAD

**Issue by cdokolas** [RobinLinus/socialmedia-leak#1]
I have Privacy Badger enabled but I still see Hackernews, Slack, and Dropbox detected (i.e. me being logged in to them). What does this mean?

**Comment by fasiha** [comment]
I just installed Privacy Badger (I have uBlock too but after some reading, I understand that the latter doesn't affect favicons). I still see most of my sites logged in. I’ll continue digging and maybe I can suggest some wording for the site.

**Comment by cdokolas** [comment]
I use uBlock as well. Turning it off had no effect (tried that before PB).

**Comment by mehdisadeghi** [comment]
After blocking all the trackers in Privacy Badger's settings page, no website's name comes up as logged in.

**Comment by TheCycoONE** [comment]
uMatrix also blocks everything

**Comment by jamesmgg** [comment]
+1 for uMatrix. It's is insanely awesome.

**Comment by RobinLinus** [comment]
uMatrix is mentioned in the "Protection" section now!
Thanks a lot for your suggestions!
