### ISSUE TITLE
Disabling third party cookies helps

### ISSUE THREAD

**Issue by jaylinski** [RobinLinus/socialmedia-leak#10]
First thing everybody should do after installing a browser:

> Block third party cookies.

Could be mentioned on your website.

**Comment by rugk** [comment]
But this does not help against this attack...

So it is not relevant here AFAIK.

**Comment by RobinLinus** [comment]
Is mentioned under prevention now.

**Comment by rugk** [comment]
Really? In my case I does not help at all. How is this supposed to help?

**Comment by jaylinski** [comment]
@rugk if you disable third party cookies, the browser doesn't send the (facebook, twitter, ...) authentication cookie with the request.

no auth-cookie == no login == no detection.

**Comment by rugk** [comment]
Okay, that's a good theory, but have you tested it in practice?
I have third party cookies disabled in Firefox and I am still shown as logged in in GitHub.

**Comment by jaylinski** [comment]
@rugk that's not a theory, I checked the http requests. cookies are missing if the request comes from a thrid party website (like https://robinlinus.github.io/socialmedia-leak/)

and I couldn't recreate the issue with github and firefox 51.

**Comment by rugk** [comment]
Okay, right now it also works for me.
