### ISSUE TITLE
stackoverflow / stackexchange not working

### ISSUE THREAD

**Issue by caub** [RobinLinus/socialmedia-leak#13]
It doesn't detect them

**Comment by RobinLinus** [comment]
Yep, they fixed it http://meta.stackoverflow.com/questions/336225/so-should-stop-leaking-information-to-other-websites-about-whether-we-are-logged

**Comment by mala** [comment]
@RobinLinus 
Not fixed yet.
http://api.ma.la/redirect_or_not/#https://stackoverflow.com/users/login-add?ssrc=head
- By Flash's bug, we can detect redirection, so validation of redirect path is meaningless for now.
- By including timing attack, protection on website side is difficult.

You say that  "the higher the pressure for platforms to fix it."
Please pressure Adobe, Browser vender.
