### ISSUE TITLE
Use google.com instead of google.de to link to PrivacyBadger

### ISSUE THREAD

**Issue by TheGroundZero** [RobinLinus/socialmedia-leak#2]
The link to Privacy Badger on your website is as follows: https://www.google.de/search?q=privacy+badger

People using this link will end up on the German Google Results page showing German results and resulting in links to the Firefox and Chrome extensions to be in German as well.  
For example, clicking on the link to the Privacy Badger Extension for Google Chrome from the Google Results page, leads to https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp?hl=de (notice the `?hl=de` on the end).

To improve usability for non-German visitors, I suggest you use the google.com domain which should redirect the user to the correct regional version of Google.

**Comment by RobinLinus** [comment]
Thanks for the hint! Fixed it

**Comment by svenluijten** [comment]
gah, literally just submitted a PR for this. Nevermind 😛

**Comment by RobinLinus** [comment]
Gnargh! Thank you anyway!!
