### ISSUE TITLE
Not working for github & facebook

### ISSUE THREAD

**Issue by ankit-kumar-jat** [RobinLinus/socialmedia-leak#30]
in my browser i have logged facebook and github both but it is not working.

**Comment by MoPaMo** [comment]
Same for github for me. If I click onto the link, I even get redirected to the favicon?

**Comment by ankit-kumar-jat** [comment]
Now those websites increased their security so that is not possible for some sites now

**Comment by MoPaMo** [comment]
That's good for the user, but one will now have to remove those sites (gonna make a pr soon)

**Comment by MoPaMo** [comment]
Spotify doesn't work either BTW
